export const adjectives = [
  "angry", "awful", "bitter", "blazing", "bloody",
  "brazen", "broken", "brutal", "burning", "busy",
  "clever", "cosmic", "crazy", "crimson", "cruel",
  "cunning", "daring", "dirty", "dizzy", "dreamy",
  "dusty", "eager", "eerie", "empty", "evil",
  "faded", "fallen", "fearful", "feral", "fickle",
  "filthy", "flaming", "flimsy", "frosty", "frozen",
  "funky", "fuzzy", "gentle", "ghostly", "giddy",
  "gloomy", "glowing", "golden", "graceful", "greedy",
  "grumpy", "guilty", "happy", "hasty", "haughty",
  "heavy", "hidden", "hollow", "holy", "horrid",
  "humble", "hungry", "icy", "idle", "jagged",
  "jealous", "jolly", "joyful", "kindly", "lazy",
  "lively", "lonely", "lovely", "loyal", "lucky",
  "lunar", "mighty", "misty", "mocking", "molten",
  "moody", "morbid", "muddy", "murky", "musty",
  "nasty", "nervous", "noble", "noisy", "nutty",
  "painful", "patient", "peaceful", "petty", "playful",
  "poison", "pretty", "prickly", "proper", "purple",
  "quiet", "rabid", "raging", "rancid", "rapid",
  "reckless", "restless", "rigid", "rowdy", "royal",
  "rugged", "rusty", "sacred", "savage", "secret",
  "shallow", "shiny", "silent", "silly", "slimy",
  "sloppy", "sneaky", "solemn", "sorry", "sparkly",
  "spooky", "steady", "sticky", "stormy", "stubborn",
  "sullen", "sunny", "tender", "thorny", "tiny",
  "toxic", "twisted", "ugly", "vicious", "vivid",
  "wary", "weary", "wicked", "windy", "worthy",
  "wrathful", "zealous",
];

export const nouns = [
  "apple", "arrow", "baby", "badger", "banner",
  "barrel", "battle", "beacon", "beetle", "blanket",
  "blossom", "body", "bottle", "boulder", "bucket",
  "bunny", "butter", "cactus", "camel", "candle",
  "captain", "carpet", "castle", "chicken", "cobra",
  "coffin", "comet", "copper", "coral", "cotton",
  "creature", "crystal", "curtain", "dagger", "darkness",
  "daughter", "demon", "desert", "diamond", "dolphin",
  "donkey", "dragon", "eagle", "elbow", "ember",
  "empire", "engine", "falcon", "feather", "finger",
  "flower", "forest", "fountain", "fossil", "freedom",
  "garden", "garlic", "giant", "goblet", "goddess",
  "goblin", "hammer", "harbor", "harvest", "heaven",
  "helmet", "hero", "honey", "hunter", "idol",
  "island", "jacket", "jester", "jewel", "jungle",
  "kitten", "ladder", "lantern", "leader", "lemon",
  "lily", "lion", "lizard", "lotus", "maiden",
  "mango", "marble", "master", "meadow", "melon",
  "merchant", "mirror", "missile", "monkey", "monster",
  "morning", "mother", "mountain", "muffin", "mushroom",
  "mustard", "needle", "nickel", "ocean", "otter",
  "outlaw", "oyster", "palace", "panther", "parrot",
  "pebble", "pepper", "phantom", "pickle", "pilgrim",
  "pillow", "pirate", "planet", "pocket", "potion",
  "pumpkin", "puppet", "puzzle", "python", "rabbit",
  "raven", "river", "rocket", "rubber", "saddle",
  "salmon", "saucer", "serpent", "shadow", "shelter",
  "silver", "spider", "spirit", "sugar", "summer",
  "sunrise", "table", "temple", "thunder", "tiger",
  "timber", "titan", "token", "tower", "treasure",
  "trumpet", "tunnel", "turkey", "turtle", "vampire",
  "velvet", "viper", "vulture", "waffle", "wagon",
  "walnut", "warrior", "water", "whisker", "widow",
  "willow", "window", "winter", "wizard", "zombie",
];

export function randomPhrase(): string {
  const pick = <T>(arr: T[]) => arr[Math.floor(Math.random() * arr.length)];
  return `${pick(adjectives)} ${pick(adjectives)} ${pick(adjectives)} ${pick(nouns)}`;
}
